import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx}", // Make sure Tailwind scans your React components
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#000000",
        "primary-fixed": "#ba88ff",
        "inverse-primary": "#7e29df",
        tertiary: "#b8ffe9",
        surface: "#0b0e14",
        "surface-dim": "#0b0e14",
        "primary-dim": "#9547f7",
        "on-secondary": "#00575b",
        "on-surface-variant": "#a9abb3",
        "tertiary-container": "#5ffbd6",
        "tertiary-fixed": "#5ffbd6",
        "secondary-dim": "#00e5ee",
        "on-tertiary-fixed": "#00483b",
        background: "#0b0e14",
        "on-tertiary-container": "#005d4c",
        "surface-variant": "#22262f",
        "surface-container-highest": "#22262f",
        "secondary-fixed": "#00f4fe",
        "on-secondary-container": "#dffdff",
        "inverse-surface": "#f9f9ff",
        "secondary-fixed-dim": "#00e5ee",
        "on-error": "#490013",
        "on-secondary-fixed": "#004346",
        "on-primary-fixed-variant": "#3f007c",
        "surface-container-lowest": "#000000",
        secondary: "#00f4fe",
        "primary-container": "#ba88ff",
        "surface-container-low": "#10131a",
        "tertiary-dim": "#45e7c3",
        "inverse-on-surface": "#52555c",
        "surface-bright": "#282c36",
        error: "#ff6e84",
        "error-dim": "#d73357",
        "secondary-container": "#00696e",
        "primary-fixed-dim": "#b075ff",
        "tertiary-fixed-dim": "#4decc8",
        "on-error-container": "#ffb2b9",
        outline: "#73757d",
        "on-background": "#ecedf6",
        "on-tertiary": "#006654",
        primary: "#c59aff",
        "on-surface": "#ecedf6",
        "outline-variant": "#45484f",
        "surface-container-high": "#1c2028",
        "on-primary-container": "#330066",
        "surface-tint": "#c59aff",
        "on-primary": "#420082",
        "on-secondary-fixed-variant": "#006266",
        "on-tertiary-fixed-variant": "#006855",
        "surface-container": "#161a21",
        "error-container": "#a70138",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
};

export default config;